version: '3.4'

services:

  postgres:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=pwd0123456789
      - POSTGRES_DB=sanic_postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  market:
    image: vaultvulp/pipenv-ubuntu:3.8
    volumes:
      - ./:/opt/market/
      - site-packages:/usr/local/lib/python3.8/site-packages
    restart: always
    depends_on:
      - postgres
    working_dir: /opt/market/
#    environment:
#      - SANIC_DB_HOST=postgres
    ports:
      - 8888:8888
    links:
      - postgres
    command: bash -c "pipenv install --system -d && python -m project"

volumes:
  site-packages: